version: '2'

services:
  gateway:
    build: .
    environment:
      - HOST_HDFS=${HOST_HDFS}
    network_mode: host
    ports: 
      - "5000"

networks:
  default:
    external:
      name: hadoop
