version: '2'

services:
  gdal:
    build: .
    image: torusbackendpython_gdal
    hostname: gdal
    container_name: gdal
    domainname: gdal
    networks:
      - gdal
    environment:
      - HOST_HDFS=${HOST_HDFS}
    ports: 
      - "5000"

networks:
    gdal:
      external: true
